version: "3.9"
services: 
  web:
    build: albertoml199904/webapp_10:latest
    restart: always
    ports:
      - 443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/concerts
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=concerts
    volumes:
      - ./mysql:/var/lib/mysql